# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import booking_pb2 as booking__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in booking_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BookingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Home = channel.unary_unary(
                '/BookingService/Home',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=booking__pb2.HomeResponse.FromString,
                _registered_method=True)
        self.GetAllBookings = channel.unary_unary(
                '/BookingService/GetAllBookings',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=booking__pb2.AllBookingsResponse.FromString,
                _registered_method=True)
        self.GetBookingsForUser = channel.unary_unary(
                '/BookingService/GetBookingsForUser',
                request_serializer=booking__pb2.UserIdRequest.SerializeToString,
                response_deserializer=booking__pb2.BookingsUserResponse.FromString,
                _registered_method=True)
        self.AddBookingForUser = channel.unary_unary(
                '/BookingService/AddBookingForUser',
                request_serializer=booking__pb2.NewBookingRequest.SerializeToString,
                response_deserializer=booking__pb2.BookingsUserResponse.FromString,
                _registered_method=True)


class BookingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Home(self, request, context):
        """Service home page
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllBookings(self, request, context):
        """Get all bookings in JSON format
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookingsForUser(self, request, context):
        """Get bookings for a specific user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBookingForUser(self, request, context):
        """Add a booking for a user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Home': grpc.unary_unary_rpc_method_handler(
                    servicer.Home,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=booking__pb2.HomeResponse.SerializeToString,
            ),
            'GetAllBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllBookings,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=booking__pb2.AllBookingsResponse.SerializeToString,
            ),
            'GetBookingsForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookingsForUser,
                    request_deserializer=booking__pb2.UserIdRequest.FromString,
                    response_serializer=booking__pb2.BookingsUserResponse.SerializeToString,
            ),
            'AddBookingForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBookingForUser,
                    request_deserializer=booking__pb2.NewBookingRequest.FromString,
                    response_serializer=booking__pb2.BookingsUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('BookingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Home(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BookingService/Home',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            booking__pb2.HomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BookingService/GetAllBookings',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            booking__pb2.AllBookingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBookingsForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BookingService/GetBookingsForUser',
            booking__pb2.UserIdRequest.SerializeToString,
            booking__pb2.BookingsUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddBookingForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/BookingService/AddBookingForUser',
            booking__pb2.NewBookingRequest.SerializeToString,
            booking__pb2.BookingsUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
